services:
  - type: web
    name: tasksentinel
    runtime: python
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: tasksentinel
      - key: SECRET_KEY
        generateValue: true
      - key: MONITOR_API_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: NODE_VERSION
        value: "18.17.0"
